### ISSUE TITLE
进程保护绕过

### ISSUE THREAD

**Issue by jixunmoe** [87owo/PYAS#11]
把 `AppData` 字样加到主程序可执行文件名下就能绕过了，如 `HELLO_AppData.EXE` （注意大小写）

https://github.com/87owo/PYAS/blob/3e0749ad60ea7b96ec2c9c14691896ea868ca23b/PYAS.py#L1222-L1223

![VirtualBox_Test_PYAS_03_07_2023_21_46_03](https://github.com/87owo/PYAS/assets/5713045/abf14ea4-9dc1-4400-8550-224dfc5ca8d6)

▲ 能阻止 `HELLO.EXE` 但是会放行 `HELLO_AppData.EXE` 执行，文件内容一致。

（碎碎念：这东西在 VirtualBox 下运行经常把 Windows 干到重启，你有什么头绪吗）

**Comment by 87owo** [comment]
感谢您的回馈，已经于2.7.6测试版修复
