### ISSUE TITLE
被智量盾了

### ISSUE THREAD

**Issue by rikimeow** [87owo/PYAS#2]
<img width="595" alt="67ac68cc1dadcacb7a63b246a8b9e43" src="https://github.com/87owo/PYAS/assets/46179978/e8fe46fc-7aae-4582-a151-8c139b459223">

**Comment by 87owo** [comment]
智量誤殺了，添加為信任就可以了

**Comment by cxzlw** [comment]
> 智量誤殺了，添加為信任就可以了

准确的说，智量把部分pyinstaller打包结果误杀了，可以试试其他打包方式，我推荐nuitka，这个我打包别的程序还没被智量淦过

**Comment by rikimeow** [comment]
> 智量誤殺了，添加為信任就可以了

最新，智量居然下线了0-0

**Comment by cxzlw** [comment]
噗哈哈哈哈哈哈哈哈哈哈居然以这种方式解决了问题
