### ISSUE TITLE
希望能开机启动到托盘，不要弹出窗口

### ISSUE THREAD

**Issue by CreeperAWA** [87owo/PYAS#21]
希望能开机启动到托盘，不要弹出窗口，在学校SEEWO一体机上用，每次要最小化很麻烦

**Comment by WhiteFoxLinux** [comment]
用火绒的弹窗拦截，拦截启动窗口只会闪一下问题不大

**Comment by CreeperAWA** [comment]
> 用火绒的弹窗拦截，拦截启动窗口只会闪一下问题不大

我都有火绒了还要PYAS干啥(

**Comment by WhiteFoxLinux** [comment]
那就用火绒（即答）
