### ISSUE TITLE
Unite that project with Xylent

### ISSUE THREAD

**Issue by HydraDragonAntivirus** [87owo/PYAS#22]
https://sourceforge.net/projects/xylent/ here is the my project

**Comment by vAlerainTech** [comment]
Bro, I don't understand why you need to write a personal profile for this issue?

**Comment by vAlerainTech** [comment]
Dude, your software is too big with 1.45GB?

**Comment by HydraDragonAntivirus** [comment]
Yes it's so big

**Comment by HydraDragonAntivirus** [comment]
now it's less than 300mb
