### ISSUE TITLE
可以细说本地扫描模型是怎么训练的吗

### ISSUE THREAD

**Issue by cxzlw** [87owo/PYAS#3]
如题

**Comment by 87owo** [comment]
先使用 pefile 分析有毒的 exe 文件的函数，并将每个文件所包含的函数储存在 PYAS_Model.py 内，扫描时进行函数对比并输出相似度 1.0~0.0，当病毒相似度到设定值则会报毒，可以参考 PYAS.py 内 pe_scan 里面的内容，要训练的话可以写入 PYAS_Model.py 清单中，外层清单为训练的文件，内层清单为文件包含的函数，建议用预设就好，不然可能会误杀正常文件

**Comment by cxzlw** [comment]
明白了，很好的设计，谢谢你的解答
